name: NewCustomCuiLianPro
main: lvhaoxuan.custom.cuilian.NewCustomCuiLianPro
version: 4.4.24
author: lvhaoxuan
depend: [LLib]
softdepend: [AttributePlus, SX-Attribute, ProtocolLib]
commands:
    cuilian:
